-- =================================================================
-- 🐰 RABBIT ERP - BẢN SQL CHẠY ĐƯỢC NGAY (FULL TEST COMMANDS)
-- =================================================================

-- Sequence: SEQ_CHIPHI | TEST: SELECT SEQ_CHIPHI.NEXTVAL FROM DUAL;
-- Sequence: SEQ_HD | TEST: SELECT SEQ_HD.NEXTVAL FROM DUAL;
-- Sequence: SEQ_HOADON | TEST: SELECT SEQ_HOADON.NEXTVAL FROM DUAL;
-- Sequence: SEQ_KH | TEST: SELECT SEQ_KH.NEXTVAL FROM DUAL;
-- Sequence: SEQ_LOAI | TEST: SELECT SEQ_LOAI.NEXTVAL FROM DUAL;
-- Sequence: SEQ_PHONG | TEST: SELECT SEQ_PHONG.NEXTVAL FROM DUAL;
-- Sequence: SEQ_TS | TEST: SELECT SEQ_TS.NEXTVAL FROM DUAL;
-- Sequence: SEQ_TV | TEST: SELECT SEQ_TV.NEXTVAL FROM DUAL;

-- VIEW: V_DS_PHONG | TEST: SELECT * FROM V_DS_PHONG WHERE ROWNUM <= 5;
CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##QL_TRO"."V_DS_PHONG" ("MA_PHONG", "TEN_PHONG", "LOAI", "GIA", "TRANG_THAI", "SO_NGUOI_TOI_DA", "SO_NGUOI", "TANG", "DIEN_HT", "NUOC_HT") AS 
  SELECT P.MA_PHONG, P.TEN_PHONG, L.TEN AS LOAI, L.GIA, P.TRANG_THAI, P.SO_NGUOI_TOI_DA, 
(SELECT COUNT(*) FROM (SELECT MA_KH FROM HOP_DONG WHERE MA_PHONG = P.MA_PHONG AND TRANG_THAI = 'CON_HIEU_LUC' UNION SELECT MA_KH FROM THANH_VIEN WHERE MA_PHONG = P.MA_PHONG)) AS SO_NGUOI, 
P.TANG, P.DIEN_HT, P.NUOC_HT FROM PHONG P JOIN LOAI_PHONG L ON P.MA_LOAI = L.MA_LOAI;

-- VIEW: V_HOPDONG | TEST: SELECT * FROM V_HOPDONG WHERE ROWNUM <= 5;
CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##QL_TRO"."V_HOPDONG" ("MA_HD", "MA_PHONG", "HO_TEN", "TEN_PHONG", "NGAY_KY", "TIEN_COC", "GIA_PHONG", "TRANG_THAI") AS 
  SELECT H.MA_HD, H.MA_PHONG, N.HO_TEN, P.TEN_PHONG, H.NGAY_KY, H.TIEN_COC, H.GIA_PHONG, H.TRANG_THAI 
FROM HOP_DONG H JOIN NGUOI_THUE N ON H.MA_KH = N.MA_KH JOIN PHONG P ON H.MA_PHONG = P.MA_PHONG;

-- VIEW: V_HOADON | TEST: SELECT * FROM V_HOADON WHERE ROWNUM <= 5;
CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##QL_TRO"."V_HOADON" ("MA_HD", "MA_KH", "THANG_NAM", "TONG_TIEN", "NGAY_LAP", "TRANG_THAI") AS 
  SELECT "MA_HD","MA_KH","THANG_NAM","TONG_TIEN","NGAY_LAP","TRANG_THAI" FROM HOA_DON;

-- VIEW: V_HOADON_DV | TEST: SELECT * FROM V_HOADON_DV WHERE ROWNUM <= 5;
CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##QL_TRO"."V_HOADON_DV" ("MA_HD", "TEN_DV") AS 
  SELECT H.MA_HD, D.TEN_DV
FROM HOA_DON_DICH_VU H
JOIN DICH_VU D ON H.MA_DV = D.MA_DV;

-- VIEW: V_TOP_HOADON | TEST: SELECT * FROM V_TOP_HOADON WHERE ROWNUM <= 5;
CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##QL_TRO"."V_TOP_HOADON" ("MA_HD", "MA_KH", "THANG_NAM", "TONG_TIEN", "NGAY_LAP", "TRANG_THAI") AS 
  SELECT "MA_HD","MA_KH","THANG_NAM","TONG_TIEN","NGAY_LAP","TRANG_THAI" FROM (
    SELECT * FROM HOA_DON ORDER BY TONG_TIEN DESC
)
WHERE ROWNUM <= 5;

-- FUNCTION: F_CON_CHO
-- LỆNH TEST: SELECT F_CON_CHO() FROM DUAL;
CREATE OR REPLACE FUNCTION F_CON_CHO(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v_count NUMBER;
    v_max NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM CHI_TIET_THUE
    WHERE MA_HD = p_MA_HD;
    SELECT P.SO_NGUOI_TOI_DA INTO v_max
    FROM PHONG P JOIN HOP_DONG H
    ON P.MA_PHONG = H.MA_PHONG
    WHERE H.MA_HD = p_MA_HD;
    IF v_count < v_max THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/

-- FUNCTION: F_DEM_NGUOI
-- LỆNH TEST: SELECT F_DEM_NGUOI(1) FROM DUAL;
CREATE OR REPLACE FUNCTION F_DEM_NGUOI(p_ma NUMBER) RETURN NUMBER IS v_count NUMBER; BEGIN SELECT COUNT(*) INTO v_count FROM ( SELECT MA_KH FROM HOP_DONG WHERE MA_PHONG = p_ma AND TRANG_THAI = 'CON_HIEU_LUC' UNION SELECT MA_KH FROM THANH_VIEN WHERE MA_PHONG = p_ma ); RETURN v_count; END;
/

-- FUNCTION: F_PHONG_TRONG
-- LỆNH TEST: SELECT F_PHONG_TRONG() FROM DUAL;
CREATE OR REPLACE FUNCTION F_PHONG_TRONG(p_MA_PHONG NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- FUNCTION: F_TONG_TIEN
-- LỆNH TEST: SELECT F_TONG_TIEN(1001) FROM DUAL;
CREATE OR REPLACE FUNCTION F_TONG_TIEN(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN),0)
    INTO v
    FROM THANH_TOAN
    WHERE MA_HD = p_MA_HD;
    RETURN v;
END;
/

-- FUNCTION: F_TONG_TIEN_HD
-- LỆNH TEST: SELECT F_TONG_TIEN_HD() FROM DUAL;
CREATE OR REPLACE FUNCTION F_TONG_TIEN_HD(p_MA_HD NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- FUNCTION: F_TONG_TIEN_HDONG
-- LỆNH TEST: SELECT F_TONG_TIEN_HDONG() FROM DUAL;
CREATE OR REPLACE FUNCTION F_TONG_TIEN_HDONG(p_MA_HD NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- PROCEDURE: P_CAPNHAT_PHONG
-- LỆNH TEST: EXEC P_CAPNHAT_PHONG();
CREATE OR REPLACE PROCEDURE P_CAPNHAT_PHONG(p_ID NUMBER)
AS BEGIN
    UPDATE PHONG SET TRANG_THAI='DA_THUE' WHERE MA_PHONG=p_ID
/

-- PROCEDURE: P_DS_HOPDONG
-- LỆNH TEST: EXEC P_DS_HOPDONG(1, 1);
CREATE OR REPLACE PROCEDURE P_DS_HOPDONG(
    ds OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN ds FOR SELECT * FROM HOP_DONG;
END;
/

-- PROCEDURE: P_TAO_HOADON
-- LỆNH TEST: EXEC P_TAO_HOADON();
CREATE OR REPLACE PROCEDURE P_TAO_HOADON(p_KH NUMBER)
AS BEGIN
    INSERT INTO HOA_DON VALUES (SEQ_HOADON.NEXTVAL, p_KH, '032026', 0, SYSDATE, 'CHUA_TRA')
/

-- PROCEDURE: P_TAO_HOPDONG
-- LỆNH TEST: EXEC P_TAO_HOPDONG(101, 500000);
CREATE OR REPLACE PROCEDURE P_TAO_HOPDONG(
    p_MA_PHONG NUMBER,
    p_TIEN_COC NUMBER
)
AS
BEGIN
    INSERT INTO HOP_DONG
    VALUES (SEQ_HD.NEXTVAL, p_MA_PHONG, SYSDATE, SYSDATE+30, p_TIEN_COC, 'CON_HIEU_LUC');
END;
/

-- PROCEDURE: P_THANHTOAN
-- LỆNH TEST: EXEC P_THANHTOAN(1);
CREATE OR REPLACE PROCEDURE P_THANHTOAN(p_HD NUMBER)
AS BEGIN
    UPDATE HOA_DON SET TRANG_THAI = 'DA_TRA' WHERE MA_HD = p_HD;
END;
/

-- PROCEDURE: P_THANH_TOAN
-- LỆNH TEST: EXEC P_THANH_TOAN(1001, 500000, 1);
CREATE OR REPLACE PROCEDURE P_THANH_TOAN(
    p_MA_HD NUMBER,
    p_SO_TIEN NUMBER,
    p_NOI_DUNG VARCHAR2
)
AS
BEGIN
    INSERT INTO THANH_TOAN
    VALUES (SEQ_TT.NEXTVAL, p_MA_HD, SYSDATE, p_SO_TIEN, p_NOI_DUNG);
END;
/

-- PROCEDURE: P_THEM_DV
-- LỆNH TEST: EXEC P_THEM_DV();
CREATE OR REPLACE PROCEDURE P_THEM_DV(p_HD NUMBER, p_DV NUMBER)
AS BEGIN
    INSERT INTO HOA_DON_DICH_VU VALUES(p_HD,p_DV)
/

-- PROCEDURE: P_THEM_KH
-- LỆNH TEST: EXEC P_THEM_KH(1);
CREATE OR REPLACE PROCEDURE P_THEM_KH(p_TEN VARCHAR2)
AS BEGIN
    INSERT INTO NGUOI_THUE (MA_KH, HO_TEN, CCCD) VALUES (SEQ_KH.NEXTVAL, p_TEN, '000000');
END;
/

-- PROCEDURE: P_THEM_NGUOI
-- LỆNH TEST: EXEC P_THEM_NGUOI(1001, 1);
CREATE OR REPLACE PROCEDURE P_THEM_NGUOI(
    p_MA_HD NUMBER,
    p_MA_NGUOI NUMBER
)
AS
BEGIN
    INSERT INTO CHI_TIET_THUE
    VALUES (SEQ_CT.NEXTVAL, p_MA_HD, p_MA_NGUOI, SYSDATE);
END;
/

-- PROCEDURE: P_XOA_HD
-- LỆNH TEST: EXEC P_XOA_HD(1);
CREATE OR REPLACE PROCEDURE P_XOA_HD(p_HD NUMBER)
AS BEGIN
    UPDATE PHONG SET TRANG_THAI = 'TRONG' WHERE MA_PHONG = (SELECT MA_PHONG FROM HOP_DONG WHERE MA_HD = p_HD);
    UPDATE HOP_DONG SET TRANG_THAI = 'HET_HAN' WHERE MA_HD = p_HD;
END;
/
