
-- 0. CLEANUP (XÓA SẠCH ĐỂ LÀM MỚI)
-- Dùng mã lệnh an toàn, nếu không có bảng thì bỏ qua chứ không báo lỗi
BEGIN
    FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN ('CHI_PHI','THANH_VIEN','TAI_SAN','HOA_DON','HOP_DONG','NGUOI_THUE','PHONG','LOAI_PHONG','DICH_VU')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN ('SEQ_LOAI','SEQ_PHONG','SEQ_KH','SEQ_HD','SEQ_HOADON','SEQ_TS','SEQ_TV','SEQ_CHIPHI')) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. TABLES
CREATE TABLE LOAI_PHONG ( MA_LOAI NUMBER PRIMARY KEY, TEN VARCHAR2(50), GIA NUMBER, GIA_DAT_COC NUMBER, DIEN_TICH NUMBER );
CREATE TABLE PHONG ( MA_PHONG NUMBER PRIMARY KEY, TEN_PHONG VARCHAR2(50), TRANG_THAI VARCHAR2(20) DEFAULT 'TRONG', SO_NGUOI_TOI_DA NUMBER, TANG NUMBER, MA_LOAI NUMBER, DIEN_HT NUMBER DEFAULT 0, NUOC_HT NUMBER DEFAULT 0, FOREIGN KEY (MA_LOAI) REFERENCES LOAI_PHONG(MA_LOAI) );
CREATE TABLE NGUOI_THUE ( MA_KH NUMBER PRIMARY KEY, HO_TEN VARCHAR2(100), SDT VARCHAR2(20), CCCD VARCHAR2(20) );
CREATE TABLE HOP_DONG ( MA_HD NUMBER PRIMARY KEY, MA_PHONG NUMBER, MA_KH NUMBER, NGAY_KY DATE DEFAULT SYSDATE, NGAY_HET_HAN DATE, TIEN_COC NUMBER, GIA_PHONG NUMBER, TRANG_THAI VARCHAR2(20) DEFAULT 'CON_HIEU_LUC', FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG), FOREIGN KEY (MA_KH) REFERENCES NGUOI_THUE(MA_KH) );
CREATE TABLE HOA_DON ( MA_HD_BILL NUMBER PRIMARY KEY, MA_HD NUMBER, THANG_NAM VARCHAR2(7), TONG_TIEN NUMBER, TRANG_THAI VARCHAR2(20) DEFAULT 'CHUA_TRA', D_CU NUMBER, D_MOI NUMBER, N_CU NUMBER, N_MOI NUMBER, FOREIGN KEY (MA_HD) REFERENCES HOP_DONG(MA_HD) );
CREATE TABLE TAI_SAN ( MA_TS NUMBER PRIMARY KEY, TEN_TS VARCHAR2(100), TINH_TRANG VARCHAR2(100), GIA_TRI NUMBER, TI_LE_MOI NUMBER, MA_PHONG NUMBER, FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG) );
CREATE TABLE THANH_VIEN ( MA_TV NUMBER PRIMARY KEY, MA_PHONG NUMBER, MA_KH NUMBER, FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG), FOREIGN KEY (MA_KH) REFERENCES NGUOI_THUE(MA_KH) );
CREATE TABLE CHI_PHI ( MA_CHI_PHI NUMBER PRIMARY KEY, LOAI_CHI_PHI NVARCHAR2(100), SO_TIEN NUMBER, NGAY_CHI DATE DEFAULT SYSDATE, GHI_CHU NVARCHAR2(255) );
CREATE TABLE DICH_VU ( MA_DV NUMBER PRIMARY KEY, TEN_DV VARCHAR2(50), DON_GIA NUMBER );

-- 2. SEQUENCES
CREATE SEQUENCE SEQ_LOAI START WITH 1;
CREATE SEQUENCE SEQ_PHONG START WITH 101;
CREATE SEQUENCE SEQ_KH START WITH 1;
CREATE SEQUENCE SEQ_HD START WITH 1001;
CREATE SEQUENCE SEQ_HOADON START WITH 2000;
CREATE SEQUENCE SEQ_TS START WITH 500;
CREATE SEQUENCE SEQ_TV START WITH 1;
CREATE SEQUENCE SEQ_CHIPHI START WITH 1;

-- 3. VIEWS
CREATE OR REPLACE VIEW V_DS_PHONG AS 
SELECT P.MA_PHONG, P.TEN_PHONG, L.TEN AS LOAI, L.GIA, P.TRANG_THAI, P.SO_NGUOI_TOI_DA, 
(SELECT COUNT(*) FROM (SELECT MA_KH FROM HOP_DONG WHERE MA_PHONG = P.MA_PHONG AND TRANG_THAI = 'CON_HIEU_LUC' UNION SELECT MA_KH FROM THANH_VIEN WHERE MA_PHONG = P.MA_PHONG)) AS SO_NGUOI, 
P.TANG, P.DIEN_HT, P.NUOC_HT FROM PHONG P JOIN LOAI_PHONG L ON P.MA_LOAI = L.MA_LOAI;

CREATE OR REPLACE VIEW V_HOPDONG AS 
SELECT H.MA_HD, H.MA_PHONG, N.HO_TEN, P.TEN_PHONG, H.NGAY_KY, H.TIEN_COC, H.GIA_PHONG, H.TRANG_THAI 
FROM HOP_DONG H JOIN NGUOI_THUE N ON H.MA_KH = N.MA_KH JOIN PHONG P ON H.MA_PHONG = P.MA_PHONG;

-- 4. TRIGGERS
CREATE OR REPLACE TRIGGER TRG_HD_DAT_PHONG
AFTER INSERT ON HOP_DONG
FOR EACH ROW
BEGIN
    UPDATE PHONG SET TRANG_THAI = 'DA_THUE' WHERE MA_PHONG = :NEW.MA_PHONG;
END;
/

CREATE OR REPLACE TRIGGER TRG_HD_TRA_PHONG
AFTER UPDATE ON HOP_DONG
FOR EACH ROW
WHEN (NEW.TRANG_THAI = 'HET_HAN')
BEGIN
    UPDATE PHONG SET TRANG_THAI = 'TRONG' WHERE MA_PHONG = :NEW.MA_PHONG;
END;
/

CREATE OR REPLACE TRIGGER TRG_KIEM_TRA_TRONG
BEFORE INSERT ON HOP_DONG
FOR EACH ROW
DECLARE
    v_status VARCHAR2(20);
BEGIN
    SELECT TRANG_THAI INTO v_status FROM PHONG WHERE MA_PHONG = :NEW.MA_PHONG;
    IF v_status = 'DA_THUE' THEN
        RAISE_APPLICATION_ERROR(-20001, '⚠️ LỖI ERP: Phòng này đang có khách ở!');
    END IF;
END;
/


-- 5. PROCEDURES & FUNCTIONS (ĐÃ PHỤC HỒI)

-- SOURCE FOR FUNCTION: F_CON_CHO
CREATE OR REPLACE FUNCTION F_CON_CHO(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v_count NUMBER;
    v_max NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM CHI_TIET_THUE
    WHERE MA_HD = p_MA_HD;

    SELECT P.SO_NGUOI_TOI_DA INTO v_max
    FROM PHONG P JOIN HOP_DONG H
    ON P.MA_PHONG = H.MA_PHONG
    WHERE H.MA_HD = p_MA_HD;

    IF v_count < v_max THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/

-- SOURCE FOR FUNCTION: F_DEM_NGUOI
CREATE OR REPLACE FUNCTION F_DEM_NGUOI(p_ma NUMBER) RETURN NUMBER IS v_count NUMBER; BEGIN SELECT COUNT(*) INTO v_count FROM ( SELECT MA_KH FROM HOP_DONG WHERE MA_PHONG = p_ma AND TRANG_THAI = 'CON_HIEU_LUC' UNION SELECT MA_KH FROM THANH_VIEN WHERE MA_PHONG = p_ma ); RETURN v_count; END;
/

-- SOURCE FOR FUNCTION: F_PHONG_TRONG
CREATE OR REPLACE FUNCTION F_PHONG_TRONG(p_MA_PHONG NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- SOURCE FOR FUNCTION: F_TONG_TIEN
CREATE OR REPLACE FUNCTION F_TONG_TIEN(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN),0)
    INTO v
    FROM THANH_TOAN
    WHERE MA_HD = p_MA_HD;

    RETURN v;
END;
/

-- SOURCE FOR FUNCTION: F_TONG_TIEN_HD
CREATE OR REPLACE FUNCTION F_TONG_TIEN_HD(p_MA_HD NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- SOURCE FOR FUNCTION: F_TONG_TIEN_HDONG
CREATE OR REPLACE FUNCTION F_TONG_TIEN_HDONG(p_MA_HD NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- SOURCE FOR PROCEDURE: P_CAPNHAT_PHONG
CREATE OR REPLACE PROCEDURE P_CAPNHAT_PHONG(p_ID NUMBER)
AS BEGIN
    UPDATE PHONG SET TRANG_THAI='DA_THUE' WHERE MA_PHONG=p_ID
/

-- SOURCE FOR PROCEDURE: P_DS_HOPDONG
CREATE OR REPLACE PROCEDURE P_DS_HOPDONG(
    ds OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN ds FOR SELECT * FROM HOP_DONG;
END;
/

-- SOURCE FOR PROCEDURE: P_TAO_HOADON
CREATE OR REPLACE PROCEDURE P_TAO_HOADON(p_KH NUMBER)
AS BEGIN
    INSERT INTO HOA_DON VALUES (SEQ_HOADON.NEXTVAL, p_KH, '032026', 0, SYSDATE, 'CHUA_TRA')
/

-- SOURCE FOR PROCEDURE: P_TAO_HOPDONG
CREATE OR REPLACE PROCEDURE P_TAO_HOPDONG(
    p_MA_PHONG NUMBER,
    p_TIEN_COC NUMBER
)
AS
BEGIN
    INSERT INTO HOP_DONG
    VALUES (SEQ_HD.NEXTVAL, p_MA_PHONG, SYSDATE, SYSDATE+30, p_TIEN_COC, 'CON_HIEU_LUC');
END;
/

-- SOURCE FOR PROCEDURE: P_THANHTOAN
CREATE OR REPLACE PROCEDURE P_THANHTOAN(p_HD NUMBER)
AS BEGIN
    UPDATE HOA_DON SET TRANG_THAI = 'DA_TRA' WHERE MA_HD = p_HD;
END;
/

-- SOURCE FOR PROCEDURE: P_THANH_TOAN
CREATE OR REPLACE PROCEDURE P_THANH_TOAN(
    p_MA_HD NUMBER,
    p_SO_TIEN NUMBER,
    p_NOI_DUNG VARCHAR2
)
AS
BEGIN
    INSERT INTO THANH_TOAN
    VALUES (SEQ_TT.NEXTVAL, p_MA_HD, SYSDATE, p_SO_TIEN, p_NOI_DUNG);
END;
/

-- SOURCE FOR PROCEDURE: P_THEM_DV
CREATE OR REPLACE PROCEDURE P_THEM_DV(p_HD NUMBER, p_DV NUMBER)
AS BEGIN
    INSERT INTO HOA_DON_DICH_VU VALUES(p_HD,p_DV)
/

-- SOURCE FOR PROCEDURE: P_THEM_KH
CREATE OR REPLACE PROCEDURE P_THEM_KH(p_TEN VARCHAR2)
AS BEGIN
    INSERT INTO NGUOI_THUE (MA_KH, HO_TEN, CCCD) VALUES (SEQ_KH.NEXTVAL, p_TEN, '000000');
END;
/

-- SOURCE FOR PROCEDURE: P_THEM_NGUOI
CREATE OR REPLACE PROCEDURE P_THEM_NGUOI(
    p_MA_HD NUMBER,
    p_MA_NGUOI NUMBER
)
AS
BEGIN
    INSERT INTO CHI_TIET_THUE
    VALUES (SEQ_CT.NEXTVAL, p_MA_HD, p_MA_NGUOI, SYSDATE);
END;
/

-- SOURCE FOR PROCEDURE: P_XOA_HD
CREATE OR REPLACE PROCEDURE P_XOA_HD(p_HD NUMBER)
AS BEGIN
    UPDATE PHONG SET TRANG_THAI = 'TRONG' WHERE MA_PHONG = (SELECT MA_PHONG FROM HOP_DONG WHERE MA_HD = p_HD);
    UPDATE HOP_DONG SET TRANG_THAI = 'HET_HAN' WHERE MA_HD = p_HD;
END;
/


-- ==========================================
-- 5. PHỤC HỒI VIEW, PROCEDURE & FUNCTION
-- ==========================================

-- SOURCE FOR VIEW: V_HOADON
CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##QL_TRO"."V_HOADON" ("MA_HD", "MA_KH", "THANG_NAM", "TONG_TIEN", "NGAY_LAP", "TRANG_THAI") AS 
  SELECT "MA_HD","MA_KH","THANG_NAM","TONG_TIEN","NGAY_LAP","TRANG_THAI" FROM HOA_DON;

-- SOURCE FOR VIEW: V_HOADON_DV
CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##QL_TRO"."V_HOADON_DV" ("MA_HD", "TEN_DV") AS 
  SELECT H.MA_HD, D.TEN_DV
FROM HOA_DON_DICH_VU H
JOIN DICH_VU D ON H.MA_DV = D.MA_DV;

-- SOURCE FOR VIEW: V_TOP_HOADON
CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##QL_TRO"."V_TOP_HOADON" ("MA_HD", "MA_KH", "THANG_NAM", "TONG_TIEN", "NGAY_LAP", "TRANG_THAI") AS 
  SELECT "MA_HD","MA_KH","THANG_NAM","TONG_TIEN","NGAY_LAP","TRANG_THAI" FROM (
    SELECT * FROM HOA_DON ORDER BY TONG_TIEN DESC
)
WHERE ROWNUM <= 5;

-- SOURCE FOR FUNCTION: F_CON_CHO
CREATE OR REPLACE FUNCTION F_CON_CHO(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v_count NUMBER;
    v_max NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM CHI_TIET_THUE
    WHERE MA_HD = p_MA_HD;
    SELECT P.SO_NGUOI_TOI_DA INTO v_max
    FROM PHONG P JOIN HOP_DONG H
    ON P.MA_PHONG = H.MA_PHONG
    WHERE H.MA_HD = p_MA_HD;
    IF v_count < v_max THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/

-- SOURCE FOR FUNCTION: F_DEM_NGUOI
CREATE OR REPLACE FUNCTION F_DEM_NGUOI(p_ma NUMBER) RETURN NUMBER IS v_count NUMBER; BEGIN SELECT COUNT(*) INTO v_count FROM ( SELECT MA_KH FROM HOP_DONG WHERE MA_PHONG = p_ma AND TRANG_THAI = 'CON_HIEU_LUC' UNION SELECT MA_KH FROM THANH_VIEN WHERE MA_PHONG = p_ma ); RETURN v_count; END;
/

-- SOURCE FOR FUNCTION: F_PHONG_TRONG
CREATE OR REPLACE FUNCTION F_PHONG_TRONG(p_MA_PHONG NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- SOURCE FOR FUNCTION: F_TONG_TIEN
CREATE OR REPLACE FUNCTION F_TONG_TIEN(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN),0)
    INTO v
    FROM THANH_TOAN
    WHERE MA_HD = p_MA_HD;
    RETURN v;
END;
/

-- SOURCE FOR FUNCTION: F_TONG_TIEN_HD
CREATE OR REPLACE FUNCTION F_TONG_TIEN_HD(p_MA_HD NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- SOURCE FOR FUNCTION: F_TONG_TIEN_HDONG
CREATE OR REPLACE FUNCTION F_TONG_TIEN_HDONG(p_MA_HD NUMBER)
RETURN NUMBER
IS v NUMBER
/

-- SOURCE FOR PROCEDURE: P_CAPNHAT_PHONG
CREATE OR REPLACE PROCEDURE P_CAPNHAT_PHONG(p_ID NUMBER)
AS BEGIN
    UPDATE PHONG SET TRANG_THAI='DA_THUE' WHERE MA_PHONG=p_ID
/

-- SOURCE FOR PROCEDURE: P_DS_HOPDONG
CREATE OR REPLACE PROCEDURE P_DS_HOPDONG(
    ds OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN ds FOR SELECT * FROM HOP_DONG;
END;
/

-- SOURCE FOR PROCEDURE: P_TAO_HOADON
CREATE OR REPLACE PROCEDURE P_TAO_HOADON(p_KH NUMBER)
AS BEGIN
    INSERT INTO HOA_DON VALUES (SEQ_HOADON.NEXTVAL, p_KH, '032026', 0, SYSDATE, 'CHUA_TRA')
/

-- SOURCE FOR PROCEDURE: P_TAO_HOPDONG
CREATE OR REPLACE PROCEDURE P_TAO_HOPDONG(
    p_MA_PHONG NUMBER,
    p_TIEN_COC NUMBER
)
AS
BEGIN
    INSERT INTO HOP_DONG
    VALUES (SEQ_HD.NEXTVAL, p_MA_PHONG, SYSDATE, SYSDATE+30, p_TIEN_COC, 'CON_HIEU_LUC');
END;
/

-- SOURCE FOR PROCEDURE: P_THANHTOAN
CREATE OR REPLACE PROCEDURE P_THANHTOAN(p_HD NUMBER)
AS BEGIN
    UPDATE HOA_DON SET TRANG_THAI = 'DA_TRA' WHERE MA_HD = p_HD;
END;
/

-- SOURCE FOR PROCEDURE: P_THANH_TOAN
CREATE OR REPLACE PROCEDURE P_THANH_TOAN(
    p_MA_HD NUMBER,
    p_SO_TIEN NUMBER,
    p_NOI_DUNG VARCHAR2
)
AS
BEGIN
    INSERT INTO THANH_TOAN
    VALUES (SEQ_TT.NEXTVAL, p_MA_HD, SYSDATE, p_SO_TIEN, p_NOI_DUNG);
END;
/

-- SOURCE FOR PROCEDURE: P_THEM_DV
CREATE OR REPLACE PROCEDURE P_THEM_DV(p_HD NUMBER, p_DV NUMBER)
AS BEGIN
    INSERT INTO HOA_DON_DICH_VU VALUES(p_HD,p_DV)
/

-- SOURCE FOR PROCEDURE: P_THEM_KH
CREATE OR REPLACE PROCEDURE P_THEM_KH(p_TEN VARCHAR2)
AS BEGIN
    INSERT INTO NGUOI_THUE (MA_KH, HO_TEN, CCCD) VALUES (SEQ_KH.NEXTVAL, p_TEN, '000000');
END;
/

-- SOURCE FOR PROCEDURE: P_THEM_NGUOI
CREATE OR REPLACE PROCEDURE P_THEM_NGUOI(
    p_MA_HD NUMBER,
    p_MA_NGUOI NUMBER
)
AS
BEGIN
    INSERT INTO CHI_TIET_THUE
    VALUES (SEQ_CT.NEXTVAL, p_MA_HD, p_MA_NGUOI, SYSDATE);
END;
/

-- SOURCE FOR PROCEDURE: P_XOA_HD
CREATE OR REPLACE PROCEDURE P_XOA_HD(p_HD NUMBER)
AS BEGIN
    UPDATE PHONG SET TRANG_THAI = 'TRONG' WHERE MA_PHONG = (SELECT MA_PHONG FROM HOP_DONG WHERE MA_HD = p_HD);
    UPDATE HOP_DONG SET TRANG_THAI = 'HET_HAN' WHERE MA_HD = p_HD;
END;
/

-- 5. INSERT DỮ LIỆU MẪU (Sử dụng Sequence để đồng bộ)
INSERT INTO DICH_VU VALUES (1, 'Điện', 4000);
INSERT INTO DICH_VU VALUES (2, 'Nước', 25000);

INSERT INTO LOAI_PHONG VALUES (1, 'Rabbit Studio', 6500000, 3000000, 30);
INSERT INTO LOAI_PHONG VALUES (2, 'Rabbit Suite', 8500000, 4000000, 45);

-- Sử dụng NEXTVAL để Sequence bắt đầu đúng từ dữ liệu mẫu
INSERT INTO PHONG (MA_PHONG, TEN_PHONG, TRANG_THAI, SO_NGUOI_TOI_DA, TANG, MA_LOAI) VALUES (SEQ_PHONG.NEXTVAL, 'Phòng 101', 'TRONG', 2, 1, 1);
INSERT INTO PHONG (MA_PHONG, TEN_PHONG, TRANG_THAI, SO_NGUOI_TOI_DA, TANG, MA_LOAI) VALUES (SEQ_PHONG.NEXTVAL, 'Phòng 102', 'TRONG', 2, 1, 1);
INSERT INTO PHONG (MA_PHONG, TEN_PHONG, TRANG_THAI, SO_NGUOI_TOI_DA, TANG, MA_LOAI) VALUES (SEQ_PHONG.NEXTVAL, 'Phòng 201', 'TRONG', 4, 2, 2);

INSERT INTO NGUOI_THUE (MA_KH, HO_TEN, SDT, CCCD) VALUES (SEQ_KH.NEXTVAL, 'Hoàng Anh Tuấn', '0912111222', '001095012345');
INSERT INTO NGUOI_THUE (MA_KH, HO_TEN, SDT, CCCD) VALUES (SEQ_KH.NEXTVAL, 'Lê Thị Diệu', '0987333444', '038092000999');

-- Ký hợp đồng mẫu
INSERT INTO HOP_DONG (MA_HD, MA_PHONG, MA_KH, TIEN_COC, GIA_PHONG, TRANG_THAI) VALUES (SEQ_HD.NEXTVAL, 101, 1, 3000000, 6500000, 'CON_HIEU_LUC');
INSERT INTO HOP_DONG (MA_HD, MA_PHONG, MA_KH, TIEN_COC, GIA_PHONG, TRANG_THAI) VALUES (SEQ_HD.NEXTVAL, 102, 2, 3000000, 6500000, 'CON_HIEU_LUC');

INSERT INTO CHI_PHI (MA_CHI_PHI, LOAI_CHI_PHI, SO_TIEN, GHI_CHU) VALUES (SEQ_CHIPHI.NEXTVAL, 'Gói Internet 1Gbps', 450000, 'Tháng 04/2026');

COMMIT;
