CREATE TABLE PHONG (
    MA_PHONG        NUMBER PRIMARY KEY,
    TEN_PHONG       VARCHAR2(50),
    GIA             NUMBER,
    SO_NGUOI_TOI_DA NUMBER,
    TRANG_THAI      VARCHAR2(20) CHECK (TRANG_THAI IN ('TRONG', 'DA_THUE'))
);

CREATE TABLE NGUOI_THUE (
    MA_NGUOI NUMBER PRIMARY KEY,
    TEN      VARCHAR2(100),
    CCCD     VARCHAR2(20) UNIQUE
);


CREATE TABLE HOP_DONG (
    MA_HD        NUMBER PRIMARY KEY,
    MA_PHONG     NUMBER,
    NGAY_BAT_DAU DATE,
    NGAY_KET_THUC DATE,
    TIEN_COC     NUMBER,
    TRANG_THAI   VARCHAR2(20) CHECK (TRANG_THAI IN ('CON_HIEU_LUC', 'HET_HAN')),
    FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)
);


CREATE TABLE CHI_TIET_THUE (
    MA_CT     NUMBER PRIMARY KEY,
    MA_HD     NUMBER,
    MA_NGUOI  NUMBER,
    NGAY_VAO  DATE,
    UNIQUE(MA_HD, MA_NGUOI),
    FOREIGN KEY (MA_HD) REFERENCES HOP_DONG(MA_HD),
    FOREIGN KEY (MA_NGUOI) REFERENCES NGUOI_THUE(MA_NGUOI)
);


CREATE TABLE THANH_TOAN (
    MA_TT    NUMBER PRIMARY KEY,
    MA_HD    NUMBER,
    NGAY_TT  DATE,
    SO_TIEN  NUMBER,
    NOI_DUNG VARCHAR2(100),
    FOREIGN KEY (MA_HD) REFERENCES HOP_DONG(MA_HD)
);


CREATE TABLE TAI_SAN (
    MA_TS    NUMBER PRIMARY KEY,
    MA_PHONG NUMBER,
    TEN_TS   VARCHAR2(100),
    GIA_TRI  NUMBER,
    FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)
);


CREATE TABLE HU_HONG (
    MA_HH      NUMBER PRIMARY KEY,
    MA_TS      NUMBER,
    NGAY_HH    DATE,
    BOI_THUONG NUMBER,
    FOREIGN KEY (MA_TS) REFERENCES TAI_SAN(MA_TS)
);



