CREATE SEQUENCE SEQ_PHONG START WITH 1;
CREATE SEQUENCE SEQ_NGUOI START WITH 1;
CREATE SEQUENCE SEQ_HD START WITH 1;
CREATE SEQUENCE SEQ_CT START WITH 1;
CREATE SEQUENCE SEQ_TT START WITH 1;

INSERT INTO PHONG VALUES (1, 'Phong A', 1000, 2, 'DA_THUE');
INSERT INTO PHONG VALUES (2, 'Phong B', 1500, 3, 'DA_THUE');
INSERT INTO PHONG VALUES (3, 'Phong C', 800, 2, 'TRONG');

INSERT INTO NGUOI_THUE VALUES (1, 'An', '111');
INSERT INTO NGUOI_THUE VALUES (2, 'Binh', '222');
INSERT INTO NGUOI_THUE VALUES (3, 'Cuong', '333');
INSERT INTO NGUOI_THUE VALUES (4, 'Dung', '444');

INSERT INTO HOP_DONG VALUES (1, 1, SYSDATE, SYSDATE+30, 500, 'CON_HIEU_LUC');
INSERT INTO HOP_DONG VALUES (2, 2, SYSDATE, SYSDATE+30, 700, 'CON_HIEU_LUC');

INSERT INTO CHI_TIET_THUE VALUES (1, 1, 1, SYSDATE);
INSERT INTO CHI_TIET_THUE VALUES (2, 2, 2, SYSDATE);
INSERT INTO CHI_TIET_THUE VALUES (3, 2, 3, SYSDATE);

INSERT INTO THANH_TOAN VALUES (1, 1, SYSDATE, 1000, 'Tien phong');
INSERT INTO THANH_TOAN VALUES (2, 2, SYSDATE, 1500, 'Tien phong');

COMMIT;

CREATE OR REPLACE VIEW V_DS_PHONG AS
SELECT P.MA_PHONG, P.TEN_PHONG, P.GIA,
       P.SO_NGUOI_TOI_DA,
       COUNT(CT.MA_NGUOI) AS SO_NGUOI,
       P.TRANG_THAI
FROM PHONG P
LEFT JOIN HOP_DONG H 
  ON P.MA_PHONG = H.MA_PHONG 
 AND H.TRANG_THAI = 'CON_HIEU_LUC'
LEFT JOIN CHI_TIET_THUE CT 
  ON H.MA_HD = CT.MA_HD
GROUP BY P.MA_PHONG, P.TEN_PHONG, P.GIA, P.SO_NGUOI_TOI_DA, P.TRANG_THAI;

CREATE OR REPLACE VIEW V_HOPDONG_TIEN AS
SELECT H.MA_HD, H.MA_PHONG,
       NVL(SUM(T.SO_TIEN),0) AS TONG_TIEN
FROM HOP_DONG H
LEFT JOIN THANH_TOAN T ON H.MA_HD = T.MA_HD
GROUP BY H.MA_HD, H.MA_PHONG;

CREATE OR REPLACE FUNCTION F_TONG_TIEN(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN),0)
    INTO v
    FROM THANH_TOAN
    WHERE MA_HD = p_MA_HD;

    RETURN v;
END;
/

CREATE OR REPLACE FUNCTION F_CON_CHO(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v_count NUMBER;
    v_max NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM CHI_TIET_THUE
    WHERE MA_HD = p_MA_HD;

    SELECT P.SO_NGUOI_TOI_DA INTO v_max
    FROM PHONG P JOIN HOP_DONG H 
    ON P.MA_PHONG = H.MA_PHONG
    WHERE H.MA_HD = p_MA_HD;

    IF v_count < v_max THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/


CREATE OR REPLACE PROCEDURE P_THEM_NGUOI(
    p_MA_HD NUMBER,
    p_MA_NGUOI NUMBER
)
AS
BEGIN
    INSERT INTO CHI_TIET_THUE
    VALUES (SEQ_CT.NEXTVAL, p_MA_HD, p_MA_NGUOI, SYSDATE);
END;
/


CREATE OR REPLACE PROCEDURE P_TAO_HOPDONG(
    p_MA_PHONG NUMBER,
    p_TIEN_COC NUMBER
)
AS
BEGIN
    INSERT INTO HOP_DONG
    VALUES (SEQ_HD.NEXTVAL, p_MA_PHONG, SYSDATE, SYSDATE+30, p_TIEN_COC, 'CON_HIEU_LUC');
END;
/

CREATE OR REPLACE PROCEDURE P_THANH_TOAN(
    p_MA_HD NUMBER,
    p_SO_TIEN NUMBER,
    p_NOI_DUNG VARCHAR2
)
AS
BEGIN
    INSERT INTO THANH_TOAN
    VALUES (SEQ_TT.NEXTVAL, p_MA_HD, SYSDATE, p_SO_TIEN, p_NOI_DUNG);
END;
/


CREATE OR REPLACE PROCEDURE P_DS_HOPDONG(
    ds OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN ds FOR SELECT * FROM HOP_DONG;
END;
/

CREATE OR REPLACE TRIGGER TRG_CHECK_SONGUOI
BEFORE INSERT ON CHI_TIET_THUE
FOR EACH ROW
DECLARE
    v_count NUMBER;
    v_max NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM CHI_TIET_THUE
    WHERE MA_HD = :NEW.MA_HD;

    SELECT P.SO_NGUOI_TOI_DA INTO v_max
    FROM PHONG P JOIN HOP_DONG H 
    ON P.MA_PHONG = H.MA_PHONG
    WHERE H.MA_HD = :NEW.MA_HD;

    IF v_count >= v_max THEN
        RAISE_APPLICATION_ERROR(-20001, 'Vuot so nguoi!');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_UPDATE_PHONG
AFTER INSERT ON HOP_DONG
FOR EACH ROW
BEGIN
    UPDATE PHONG
    SET TRANG_THAI = 'DA_THUE'
    WHERE MA_PHONG = :NEW.MA_PHONG;
END;
/


CREATE OR REPLACE PACKAGE PKG_PHONG_TRO AS

    -- Tính tổng tiền
    FUNCTION F_TONG_TIEN(p_MA_HD NUMBER) RETURN NUMBER;

    -- Thêm người thuê
    PROCEDURE P_THEM_NGUOI(p_MA_HD NUMBER, p_MA_NGUOI NUMBER);

    -- Tạo hợp đồng
    PROCEDURE P_TAO_HOPDONG(p_MA_PHONG NUMBER, p_TIEN_COC NUMBER);

    -- Thanh toán
    PROCEDURE P_THANH_TOAN(p_MA_HD NUMBER, p_SO_TIEN NUMBER, p_NOI_DUNG VARCHAR2);

    -- Lấy danh sách hợp đồng (REF CURSOR)
    PROCEDURE P_DS_HOPDONG(ds OUT SYS_REFCURSOR);

    -- TOP hợp đồng (có ROWNUM)
    PROCEDURE P_TOP_HOPDONG(ds OUT SYS_REFCURSOR, p_TOP NUMBER);

END PKG_PHONG_TRO;
/


CREATE OR REPLACE PACKAGE BODY PKG_PHONG_TRO AS

-- ========================
-- FUNCTION
-- ========================
FUNCTION F_TONG_TIEN(p_MA_HD NUMBER)
RETURN NUMBER
IS
    v NUMBER;
BEGIN
    SELECT NVL(SUM(SO_TIEN),0)
    INTO v
    FROM THANH_TOAN
    WHERE MA_HD = p_MA_HD;

    RETURN v;
END;

-- ========================
-- PROCEDURE: THÊM NGƯỜI
-- ========================
PROCEDURE P_THEM_NGUOI(p_MA_HD NUMBER, p_MA_NGUOI NUMBER)
AS
BEGIN
    INSERT INTO CHI_TIET_THUE
    VALUES (SEQ_CT.NEXTVAL, p_MA_HD, p_MA_NGUOI, SYSDATE);
END;

-- ========================
-- PROCEDURE: TẠO HỢP ĐỒNG
-- ========================
PROCEDURE P_TAO_HOPDONG(p_MA_PHONG NUMBER, p_TIEN_COC NUMBER)
AS
BEGIN
    INSERT INTO HOP_DONG
    VALUES (SEQ_HD.NEXTVAL, p_MA_PHONG, SYSDATE, SYSDATE+30, p_TIEN_COC, 'CON_HIEU_LUC');
END;

-- ========================
-- PROCEDURE: THANH TOÁN
-- ========================
PROCEDURE P_THANH_TOAN(p_MA_HD NUMBER, p_SO_TIEN NUMBER, p_NOI_DUNG VARCHAR2)
AS
BEGIN
    INSERT INTO THANH_TOAN
    VALUES (SEQ_TT.NEXTVAL, p_MA_HD, SYSDATE, p_SO_TIEN, p_NOI_DUNG);
END;

-- ========================
-- PROCEDURE: DANH SÁCH
-- ========================
PROCEDURE P_DS_HOPDONG(ds OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN ds FOR
    SELECT * FROM HOP_DONG;
END;

-- ========================
-- PROCEDURE: TOP (ROWNUM)
-- ========================
PROCEDURE P_TOP_HOPDONG(ds OUT SYS_REFCURSOR, p_TOP NUMBER)
AS
BEGIN
    OPEN ds FOR
    SELECT * FROM (
        SELECT H.MA_HD, H.MA_PHONG, SUM(T.SO_TIEN) TONG_TIEN
        FROM HOP_DONG H
        JOIN THANH_TOAN T ON H.MA_HD = T.MA_HD
        GROUP BY H.MA_HD, H.MA_PHONG
        ORDER BY TONG_TIEN DESC
    )
    WHERE ROWNUM <= p_TOP;
END;

END PKG_PHONG_TRO;
/

SELECT PKG_PHONG_TRO.F_TONG_TIEN(1) FROM DUAL;